# fly.toml app configuration file generated for icy-fog-1916 on 2023-06-17T08:15:47+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "icy-fog-1916"
primary_region = "mad"
kill_signal = "SIGTERM"

[env]
  PHX_HOST = "icy-fog-1916.fly.dev"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
